Support CUDA 11.2
chainer/chainer-test pull request #635
Opened 2021-02-19 16:37 UTC by takagi

This PR includes changes to support CUDA 11.2. Note that we have to merge #633 first as CUDA 11.2 does not support cuDNN 8.0.

2021-02-23 04:24 UTC, kmaehashi commented
#633 merged! 🚀

2021-02-23 04:52 UTC, takagi commented
pfnCI, test this please.

2021-02-23 06:45 UTC, kmaehashi requested changes

2021-02-23 06:45 UTC, kmaehashi commented on docker.py
> +    'cuda112': ['cudnn80-cuda112', 'cudnn81-cuda112'],
```suggestion
    'cuda112': ['cudnn81-cuda112'],
```

2021-02-23 06:45 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-23 12:35 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-23 13:49 UTC, kmaehashi commented on docker.py
> +    libnccl_dev='libnccl-dev_2.8.3-1+cuda11.2_amd64.deb',
```suggestion
    libnccl2='libnccl2_2.8.4-1+cuda11.2_amd64',
    libnccl_dev='libnccl-dev_2.8.4-1+cuda11.2_amd64',
```

2021-02-23 13:49 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-23 14:44 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-23 15:32 UTC, kmaehashi commented on docker.py
> +    libnccl_dev='libnccl-dev_2.8.4-1+cuda11.2_amd64',
```suggestion
    libnccl2='libnccl2_2.8.3-1+cuda11.2_amd64',
    libnccl_dev='libnccl-dev_2.8.3-1+cuda11.2_amd64',
```

2021-02-23 15:32 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-23 20:02 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-23 20:24 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-24 00:27 UTC, emcastillo commented
Jenkins, test this please

2021-02-24 07:35 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-24 09:42 UTC, emcastillo commented
CI is unrelated

2021-02-24 10:00 UTC, merged